# Generated by Django 5.2.4 on 2025-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Image du plat'),
        ),
    ]
